databases:
  - name: productionDatabase
    databaseName: productionDatabase
    user: productionDatabase

services:
  - type: web
    name: DjangoApp
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn django_portfolio.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: DjangoApp
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
