name: Build and Deploy

on:
  push:
    branches:
      - main  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  

    - name: Install dependencies
      run: poetry install

    - name: Run build script
      run: |
        chmod +x build.sh
        ./build.sh

    - name: Deploy to Render
      run: |
        poetry run gunicorn django_portfolio.wsgi:application
    

